services:
  - type: web
    name: stegostudy-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn base:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: stegostudy-db
          property: connectionString

databases:
  - name: stegostudy-db
    ipAllowList: [] 